site_name: Robozito 2020

theme:
  name: 'material'
  features:
    - 'navigation.tabs'
    - 'navigation.sections' 
    - 'toc.integrate'
#  logo: assets/logo.png
#  favicon: images/favicon.png

  palette:
  - scheme: 'slate'
    primary: 'red'
    accent: 'orange'

  font:
    text: 'Roboto' 
    code: 'Roboto Mono'

  docs_dir: docs-src
  site_dir: docs

# Copyright
copyright: 'Copyright &copy; Luis Bueno @ Insper'

# Navegação

markdown_extensions:
  - toc:
      permalink: true
nav:
  - Home: index.md
  - 'Corte a Laser': laser.md
