site_name: 'Robozito 2020'
repo_name: 'LuisHFB/Doc_Robozito'
repo_url: 'https://github.com/LuisHFB/Doc_Robozito'
site_description: 'Robo OpenSource para atividade de entrosamento de grupo'
copyright: 'Copyright &copy; Luis Bueno @ Insper'

theme: 
  name: material
  language: pt
  features:
    - 'navigation.tabs'
    - 'navigation.sections' 
    - 'toc.integrate'
# logo: assets/logo
# favicon: images/favicon

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red 
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: 'Roboto' 
    code: 'Roboto Mono'
  
# Navegação
nav:
  - Home: index.md

  - Eletrônica:
    - 'Projetando a placa eletrônica': 'eletronica/projeto3.md'
    - 'Usinagem de PCB': 'eletronica/usinagemPcb.md'
    - 'Solda': 'eletronica/solda.md' 
    - 'Montagem da Eletrônica': 'eletronica/montagemEletronica.md'
    #- 'Arquivos da placa eletrônica' : 'link3'
  - Programação:
    - 'Configuração da Arduino IDE': 'programacao/configArduinoIDE.md'
    - 'Código': 'programacao/oCodigo.md'
    - 'Gravando o código na ESP8266': 'programacao/gravandoESP.md'
  - Corpo:
    - 'Projetando o Corpo': 'corpo/projeto1.md'
    - 'Corte à Laser': laser.md
    #- 'Arquivos do corpo': 'link' 
  - Braços: 
    - 'Projetando os Braços': 'braco/projeto2.md'
    - 'Rodas e Apoio': 'braco/rodaApoio.md'
    - 'Impressão 3D': 'braco/3dPrint.md'
    - 'Arquivos de impressão 3d' : 'braco/files/STLPeçasImpressas.zip'
  - Montagem: 
    - 'BOM': 'montagem/montagem.md'

# extras
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.magiclink
  - attr_list

plugins:
    - search
    - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/LuisHFB/Doc_Robozito'
  alternate:
    # Switch to English
    - name: English
      link: 'https://luishfb.github.io/Doc_RobozitoEN/'
      lang: en
    # Switch to Portuguese
    - name: Português
      link: 'https://luishfb.github.io/Doc_Robozito/'
      lang: pt
