site_name: Robozito 2020

theme:
  name: 'material'
  features:
    - 'navigation.tabs'
    - 'navigation.sections' 
    - 'toc.integrate'
#  icon:
#    repo: "fontawesome/brands/github"
#  logo: assets/logo.png
#  favicon: images/favicon.png

  palette:
  - scheme: 'slate'
    primary: 'red'
    accent: 'orange'

  font:
    text: 'Roboto' 
    code: 'Roboto Mono'

  docs_dir: docs
  site_dir: docs
  
  repo_name: 'LuisHFB/Doc_Robozito'
  repo_url: 'https://github.com/LuisHFB/Doc_Robozito'
  
# Copyright
copyright: 'Copyright &copy; Luis Bueno @ Insper'

# Navegação

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Home: index.md
    
  - Corpo:
    - 'Projetando o Corpo': 'corpo/projeto1.md'
    - 'Corte à Laser': laser.md
    #- 'Arquivos do corpo': 'link' 
  - Braços: 
    - 'Projetando os Braços': 'braco/projeto2.md'
    - 'Motores e Suporte': 'braco/moterEsuporte.md'
    - 'Impressão 3D': 'braco/3dPrint.md'
    #- 'Arquivos de impressão 3d' : 'link2'
  - Eletrônica:
    - 'Projetando a placa eletrônica': 'eletronica/projeto3.md'
    - 'Usinagem de PCB': 'eletronica/usinagemPcb.md'
    - 'Solda': 'eletronica/solda.md' 
    - 'Montagem da Eletrônica': 'eletronica/montagemEletronica.md'
    #- 'Arquivos da placa eletrônica' : 'link3'
  - Programação:
    - 'Configuração da Arduino IDE': 'programacao/configArduinoIDE.md'
    - 'Código': 'programacao/oCodigo.md'
    - 'Gravando o código na ESP8266': 'programacao/gravandoESP.md'
  - Montagem: 
    - 'montagem/montagem.md'

